import React, { useState } from 'react';
import { JournalConfig, CoffeeSlogan } from '../types';
import { PRELOADED_SLOGANS, COFFEE_VIBE_CATEGORIES } from '../data/coffeeSlogans';
import { Coffee, Sparkles, Wand2, Check, RefreshCw } from 'lucide-react';

interface SloganManagerProps {
  config: JournalConfig;
  onChangeConfig: (updated: Partial<JournalConfig>) => void;
}

export const SloganManager: React.FC<SloganManagerProps> = ({ config, onChangeConfig }) => {
  const [selectedCategory, setSelectedCategory] = useState<string>('all');
  const [customVibes, setCustomVibes] = useState<string>('');
  const [aiCategory, setAiCategory] = useState<string>('aesthetic');
  const [aiSlogans, setAiSlogans] = useState<CoffeeSlogan[]>([]);
  const [isLoading, setIsLoading] = useState<boolean>(false);
  const [apiError, setApiError] = useState<string | null>(null);

  // Filter slogans based on Category
  const filteredPreloaded = selectedCategory === 'all' 
    ? PRELOADED_SLOGANS 
    : PRELOADED_SLOGANS.filter(s => s.category === selectedCategory);

  // Call server-side secure Gemini backend to generate slogans
  const handleGenerateAISlogans = async () => {
    setIsLoading(true);
    setApiError(null);
    try {
      const response = await fetch('/api/generate-slogans', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          category: aiCategory,
          vibes: customVibes
        }),
      });

      const data = await response.json();

      if (!response.ok) {
        throw new Error(data.error || "Failed to contact Gemini engine. Check your API configuration.");
      }

      if (data.slogans && Array.isArray(data.slogans)) {
        setAiSlogans(data.slogans);
      } else {
        throw new Error("Invalid response schema generated by AI. Please try again.");
      }
    } catch (err: any) {
      console.error(err);
      setApiError(err.message || "An unexpected error occurred during AI coffee-prompt brewing.");
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div className="flex flex-col gap-6" id="kdp_slogan_panel">
      {/* Active selected slogan box */}
      <div className="p-5 border border-zinc-250 bg-zinc-50/50">
        <h4 className="text-[10px] font-bold uppercase tracking-widest text-zinc-550 font-mono flex items-center gap-1.5 mb-2.5">
          <Coffee size={12} className="text-zinc-950" /> Active Selected Motto (Prints on Page 3)
        </h4>
        <div className="relative p-4 bg-white border border-zinc-200">
          <p className="font-serif italic text-base text-zinc-900 leading-relaxed">
            "{config.selectedSlogan}"
          </p>
          {config.selectedSloganAuthor && (
            <p className="text-[10px] font-mono uppercase tracking-wider text-zinc-400 text-right mt-2">
              — {config.selectedSloganAuthor}
            </p>
          )}
        </div>
      </div>

      {/* Tabs of selection: Preloaded vs Gemini AI */}
      <div className="flex flex-col gap-5">
        <div className="border-b border-zinc-200 pb-1.5">
          <h3 className="text-xs font-bold uppercase tracking-wider text-zinc-950 font-mono">
            Slogan Customizer (Target Female Coffee Lovers)
          </h3>
        </div>

        {/* --- SECTION 1: GEMINI AI GENERATOR --- */}
        <div className="p-5 border border-zinc-300 bg-white">
          <div className="flex flex-wrap items-center justify-between gap-2 mb-3">
            <h4 className="text-xs font-bold uppercase tracking-widest text-zinc-950 flex items-center gap-1.5 font-mono">
              <Sparkles size={14} className="text-zinc-900" />
              Brew Custom Motto with Gemini AI
            </h4>
            <span className="text-[9px] bg-zinc-100 border border-zinc-250 text-zinc-700 font-bold px-2 py-0.5 uppercase tracking-wider font-mono">
              Secure Server Proxy
            </span>
          </div>
          
          <p className="text-[11px] text-zinc-500 leading-relaxed mb-4 font-serif">
            Instantly formulate tailored slogans for your female notebook target market (funny, cozy, cute, or intellectual). Generates highly personalized aesthetic margins.
          </p>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mb-4">
            <div>
              <label className="block text-[10px] font-bold uppercase tracking-wider text-zinc-500 mb-1 font-mono">
                Slogan Mood Vibe:
              </label>
              <select
                value={aiCategory}
                onChange={(e) => setAiCategory(e.target.value)}
                className="w-full text-xs p-2.5 rounded-none border border-zinc-300 bg-zinc-50 focus:bg-white focus:border-zinc-950 outline-none"
              >
                {COFFEE_VIBE_CATEGORIES.map(cat => (
                  <option key={cat.value} value={cat.value}>{cat.label}</option>
                ))}
              </select>
            </div>

            <div>
              <label className="block text-[10px] font-bold uppercase tracking-wider text-zinc-500 mb-1 font-mono">
                Custom Keywords (Optional):
              </label>
              <input
                type="text"
                value={customVibes}
                onChange={(e) => setCustomVibes(e.target.value)}
                placeholder="e.g. Rainy days, plant lover, cozy bookstore"
                className="w-full text-xs p-2.5 rounded-none border border-zinc-300 bg-zinc-50 focus:bg-white focus:border-zinc-950 outline-none"
              />
            </div>
          </div>

          <button
            onClick={handleGenerateAISlogans}
            disabled={isLoading}
            className="w-full py-3 px-4 bg-zinc-950 hover:bg-zinc-900 border border-zinc-800 text-white rounded-none text-[10px] font-bold uppercase tracking-wider transition-colors flex items-center justify-center gap-2 cursor-pointer"
          >
            {isLoading ? (
              <>
                <RefreshCw size={12} className="animate-spin" />
                Roasting coffee ideas with Gemini AI...
              </>
            ) : (
              <>
                <Wand2 size={12} />
                Generate Bespoke Slogans
              </>
            )}
          </button>

          {/* AI Output box */}
          {apiError && (
            <div className="mt-4 p-3.5 border border-red-200 bg-red-50/40 text-red-700 text-xs font-serif">
              <p className="font-sans font-bold uppercase text-[10px] tracking-wider text-red-805">☕ Brewing Error:</p>
              <p className="mt-1 leading-relaxed">{apiError}</p>
              <p className="text-[10px] text-red-500 mt-2 font-mono">
                Verify your GEMINI_API_KEY environment variable is configured in the Secrets panel in AI Studio settings.
              </p>
            </div>
          )}

          {aiSlogans.length > 0 && !isLoading && (
            <div className="mt-5 flex flex-col gap-3">
              <span className="text-[10px] font-bold text-zinc-850 uppercase font-mono tracking-wider">
                Freshly Roasted AI Slogans:
              </span>
              <div className="grid grid-cols-1 gap-2">
                {aiSlogans.map((slogan, idx) => {
                  const isCurrent = slogan.text === config.selectedSlogan;
                  return (
                    <button
                      key={idx}
                      onClick={() => onChangeConfig({
                        selectedSlogan: slogan.text,
                        selectedSloganAuthor: slogan.author || 'AI Inspired'
                      })}
                      className={`text-left p-3.5 border text-xs transition-all relative flex flex-col gap-1 cursor-pointer ${
                        isCurrent 
                          ? 'border-zinc-950 bg-zinc-50/50' 
                          : 'border-zinc-200 bg-white hover:border-zinc-400 hover:bg-zinc-50/20'
                      }`}
                    >
                      <p className="font-serif italic text-zinc-900 pr-16 leading-relaxed">
                        "{slogan.text}"
                      </p>
                      <div className="flex items-center justify-between mt-1">
                        <span className="text-[10px] text-zinc-500 font-mono">
                          — {slogan.author || 'Cozy AI'} &bull; {slogan.category}
                        </span>
                        {isCurrent && (
                          <span className="text-[8px] bg-zinc-950 text-white px-2 py-0.5 uppercase tracking-wider font-bold flex items-center gap-0.5">
                            <Check size={8} /> Selected
                          </span>
                        )}
                      </div>
                    </button>
                  );
                })}
              </div>
            </div>
          )}
        </div>

        {/* --- SECTION 2: HAND-CURATED FAVORITES --- */}
        <div className="p-5 border border-zinc-200 bg-zinc-50/30">
          <div className="flex flex-wrap items-center justify-between gap-3 mb-4">
            <h4 className="text-[11px] font-bold uppercase tracking-wider text-zinc-800 font-mono">
              Hand-Curated Cafe Slogan Library
            </h4>

            {/* Filter tags */}
            <div className="flex flex-wrap gap-1 bg-zinc-100 p-0.5 border border-zinc-200">
              {['all', 'aesthetic', 'cozy', 'motivational', 'funny'].map((tag) => (
                <button
                  key={tag}
                  onClick={() => setSelectedCategory(tag)}
                  className={`text-[8px] font-mono font-bold uppercase py-1 px-2.5 transition-all cursor-pointer ${
                    selectedCategory === tag
                      ? 'bg-zinc-950 text-white font-bold'
                      : 'text-zinc-650 hover:text-zinc-900 hover:bg-zinc-200/50'
                  }`}
                >
                  {tag}
                </button>
              ))}
            </div>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-3 max-h-76 overflow-y-auto pr-1">
            {filteredPreloaded.map((slogan, idx) => {
              const isCurrent = slogan.text === config.selectedSlogan;
              return (
                <button
                  key={idx}
                  onClick={() => onChangeConfig({
                    selectedSlogan: slogan.text,
                    selectedSloganAuthor: slogan.author || ''
                  })}
                  className={`text-left p-3.5 border transition-all text-xs flex flex-col justify-between gap-2.5 relative cursor-pointer ${
                    isCurrent 
                      ? 'border-zinc-950 bg-white' 
                      : 'border-zinc-200 bg-white hover:border-zinc-400 hover:bg-zinc-50/30'
                  }`}
                >
                  <p className="font-serif italic text-zinc-700 leading-relaxed pr-6">
                    "{slogan.text}"
                  </p>
                  <div className="flex items-center justify-between text-[10px] w-full text-zinc-400 font-mono mt-auto pt-1">
                    <span>— {slogan.author || 'Unknown'}</span>
                    <span className="capitalize text-[8px] font-bold tracking-wider py-0.5 px-2 bg-zinc-100 text-zinc-500 uppercase border border-zinc-200">
                      {slogan.category}
                    </span>
                  </div>
                  {isCurrent && (
                    <span className="absolute top-2.5 right-2.5 text-white bg-zinc-950 p-0.5">
                      <Check size={10} strokeWidth={3} />
                    </span>
                  )}
                </button>
              );
            })}
          </div>
        </div>

        {/* --- SECTION 3: WRITE YOUR OWN --- */}
        <div className="p-5 border border-zinc-200 bg-white">
          <h4 className="text-[10px] font-bold text-zinc-900 uppercase tracking-widest font-mono mb-3.5">
            ✏️ Write Your Own Custom Mottos
          </h4>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-3">
            <div className="md:col-span-2">
              <label className="block text-[10px] font-bold uppercase tracking-wider text-zinc-500 mb-1 font-mono">
                Slogan Text:
              </label>
              <input
                type="text"
                value={config.selectedSlogan}
                onChange={(e) => onChangeConfig({ selectedSlogan: e.target.value })}
                placeholder="Enter your custom motto"
                className="w-full text-xs p-2.5 rounded-none border border-zinc-300 bg-zinc-50 focus:bg-white focus:border-zinc-950 outline-none"
              />
            </div>
            <div>
              <label className="block text-[10px] font-bold uppercase tracking-wider text-zinc-500 mb-1 font-mono">
                Author Attribution:
              </label>
              <input
                type="text"
                value={config.selectedSloganAuthor}
                onChange={(e) => onChangeConfig({ selectedSloganAuthor: e.target.value })}
                placeholder="e.g. Traditional, Jane Doe"
                className="w-full text-xs p-2.5 rounded-none border border-zinc-300 bg-zinc-50 focus:bg-white focus:border-zinc-950 outline-none"
              />
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};
